"use client";

import { useState, type FormEvent } from "react";
import { usePrototype } from "@/components/prototype-provider";
import { Button, PageHeading } from "@/components/ui";

export default function SettingsPage() {
  const { notify } = usePrototype();
  const [name, setName] = useState("An Nguyễn");
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); notify("Đã lưu thay đổi trong bản dùng thử."); }
  return <div className="app-content"><PageHeading title="Cài đặt" description="Quản lý thông tin cá nhân và tùy chọn của bạn."/><div className="settings-layout"><nav className="card settings-tabs" aria-label="Mục cài đặt"><a href="#profile">Thông tin cá nhân</a><a href="#preferences">Tùy chọn</a><a href="#account">Tài khoản</a></nav><div style={{ display: "grid", gap: 13 }}><section id="profile" className="card settings-panel"><h2>Thông tin cá nhân</h2><p>Cập nhật thông tin xuất hiện trong tài khoản của bạn.</p><form onSubmit={save}><div className="field"><label htmlFor="settings-name">Tên hiển thị</label><input className="input" id="settings-name" value={name} onChange={(event) => setName(event.target.value)} required/></div><div className="field"><label htmlFor="settings-email">Email</label><input className="input" id="settings-email" type="email" value="an@example.com" readOnly/><span className="field-help">Đây là email minh họa trong prototype.</span></div><div className="field"><label htmlFor="settings-language">Ngôn ngữ</label><select className="select" id="settings-language" defaultValue="vi"><option value="vi">Tiếng Việt</option></select></div><Button type="submit">Lưu thay đổi</Button></form></section><section id="preferences" className="card settings-panel"><h2>Tùy chọn thông báo</h2><p>Chọn những cập nhật bạn muốn nhận về hoạt động của mình.</p><label className="preference-row"><span><strong>Email cập nhật sản phẩm</strong><small>Thông tin về tính năng mới và cách sử dụng.</small></span><input type="checkbox" defaultChecked aria-label="Nhận email cập nhật sản phẩm"/></label><label className="preference-row"><span><strong>Mẹo và gợi ý nội dung</strong><small>Gợi ý prompt phù hợp với lĩnh vực.</small></span><input type="checkbox" aria-label="Nhận mẹo và gợi ý nội dung"/></label></section><section id="account" className="card settings-panel"><h2>Tài khoản</h2><p>Thông tin trạng thái minh họa của tài khoản trong prototype.</p><div className="list-row" style={{ paddingInline: 0 }}><span className="list-row-main"><span className="list-row-title" style={{ display: "block" }}>Gói hiện tại</span><span className="list-row-meta">Miễn phí · Chưa có xác thực thật</span></span><span className="pill">Đang dùng thử</span></div></section></div></div></div>;
}
